name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: stable

      - name: Crear archivo .env con secret
        run: echo "APP_ENV=${{ secrets.APP_ENV }}" > .env

      - name: Obtener dependencias
        run: flutter pub get

      - name: Compilar APK
        run: flutter build apk --release

      - name: Subir artefacto APK
        uses: actions/checkout@v4.1.1
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
